In [2]:
person = input('Enter your name: ')
print('Hello', person)

Enter your name: Hi
Hello Hi


In [7]:

import plotly.plotly as py

from plotly.graph_objs import *

trace0 = Scatter(
    x=[1, 2, 3, 4],
    y=[10, 15, 13, 17]
)
trace1 = Scatter(
    x=[1, 2, 3, 4],
    y=[16, 5, 11, 9]
)
data = Data([trace0, trace1])

py.iplot(data, filename = 'basic-line')


In [8]:
import numpy as np
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.empty((2,6))

array([[  1.28943095e-311,   2.86558075e-322,   0.00000000e+000,
          0.00000000e+000,   1.28805145e-311,   8.75983079e+164],
       [  5.20078145e-090,   2.42259158e-052,   1.00525615e-047,
          7.86350678e-067,   6.48224659e+170,   5.82471487e+257]])

In [23]:
import numpy as np
l= [x for x in range(50) if x%2==1]
arr=np.array(l)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [42]:
from numpy import array
a = array([[1,2,3],[4,5,6],[7,8,9]])
a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [55]:
arr=np.empty((8,4))

for i in range(4):
    arr[:,i]=i
print(arr)

[[ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]
 [ 0.  1.  2.  3.]]


In [62]:
import numpy as np
names=np.array(['mitali','priyankaaa','mitali','rashmi','nayan'])
np.unique(names)

array(['mitali', 'nayan', 'priyankaaa', 'rashmi'], 
      dtype='<U10')

In [61]:

l=['mitali','priyankaaa','mitali','rashmi','nayan']
set(l)

{'mitali', 'nayan', 'priyankaaa', 'rashmi'}

In [63]:
import numpy as np
names=np.array(['mitali','priyankaaa','mitali','rashmi','nayan'])
set(names)

{'mitali', 'nayan', 'priyankaaa', 'rashmi'}